package hcmute.edu.vn.discord.entity.enums;

public enum EAuditAction {
    SERVER_UPDATE,
    CHANNEL_CREATE,
    CHANNEL_UPDATE,
    CHANNEL_DELETE,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,
    MEMBER_ROLE_UPDATE,
    MEMBER_KICK,
    MEMBER_BAN,
    MEMBER_UNBAN,
    INVITE_CREATE,
    INVITE_DELETE,
    ADMIN_BAN_USER,
    ADMIN_UNBAN_USER,
    ADMIN_UPDATE_USER,
    ADMIN_DELETE_SERVER,
    ADMIN_UPDATE_SERVER,
    ADMIN_DELETE_MESSAGE,
    ADMIN_RESTORE_MESSAGE
}